#!/bin/bash
#
# gets est.fa.gz, unzips it, truncates it to be less than 4GB for
# some tests, and makes multiple copies to avoid cache issues.
#

wget http://hgdownload.cse.ucsc.edu/goldenpath/hg19/bigZips/est.fa.gz
gunzip est.fa.gz
split -l 80000000 est.fa && rm est.fa xab && mv xaa est.trunc.fa
cp est.trunc.fa est.trunc.fa.0
gzip est.trunc.fa.0
mv est.trunc.fa est.trunc.fa.0

##
## skip these lines if you don't want multiple copies!
##
for n in $( seq 1 4 )
do
    cp est.trunc.fa.0 est.trunc.fa.${n}
    cp est.trunc.fa.0.gz est.trunc.fa.${n}.gz
done
